Visual Studio 2015 issues are there again " 1>unrimp\renderer\rendererruntime\include\rendererruntime\resource\compositornode\pass\compositorpassfactory.h(47): error C2220: warning treated as error - no 'object' file generated (compiling source file src\Resource\CompositorNode\Pass\CompositorPassFactory.cpp) 1>unrimp\renderer\rendererruntime\include\rendererruntime\resource\compositornode\pass\compositorpassfactory.h(47): warning C4275: non dll-interface class 'RendererRuntime::ICompositorPassFactory' used as base for dll-interface class 'RendererRuntime::CompositorPassFactory' (compiling source file src\Resource\CompositorNode\Pass\CompositorPassFactory.cpp) 1>  unrimp\renderer\rendererruntime\include\rendererruntime\resource\compositornode\pass\icompositorpassfactory.h(62): note: see declaration of 'RendererRuntime::ICompositorPassFactory' (compiling source file src\Resource\CompositorNode\Pass\CompositorPassFactory.cpp) 1>  unrimp\renderer\rendererruntime\include\rendererruntime\resource\compositornode\pass\compositorpassfactory.h(46): note: see declaration of 'RendererRuntime::CompositorPassFactory' (compiling source file src\Resource\CompositorNode\Pass\CompositorPassFactory.cpp) 1>unrimp\renderer\rendererruntime\include\rendererruntime\resource\compositornode\pass\compositorpassfactory.h(47): error C2220: warning treated as error - no 'object' file generated (compiling source file src\Resource\CompositorNode\CompositorNodeResourceManager.cpp) 1>unrimp\renderer\rendererruntime\include\rendererruntime\resource\compositornode\pass\compositorpassfactory.h(47): warning C4275: non dll-interface class 'RendererRuntime::ICompositorPassFactory' used as base for dll-interface class 'RendererRuntime::CompositorPassFactory' (compiling source file src\Resource\CompositorNode\CompositorNodeResourceManager.cpp) 1>  unrimp\renderer\rendererruntime\include\rendererruntime\resource\compositornode\pass\icompositorpassfactory.h(62): note: see declaration of 'RendererRuntime::ICompositorPassFactory' (compiling source file src\Resource\CompositorNode\CompositorNodeResourceManager.cpp) "
Stefan Wezel wrote an email with detailed information. Left myself a comment inside the code to mark places which differ from the rest. No new topic, came up in PixelLight over 15 years as well. Just a matter of API export strategy which I need to reevaluate since the renderer runtime interface became more complex as the renderer backend interface.