Renderer toolkit: Reviewed "2>unrimp\Renderer\RendererToolkit\include\RendererToolkit/Helper/CacheManager.h(182): warning C4625: 'RendererToolkit::CacheManager': copy constructor was implicitly defined as deleted (compiling source file src\AssetCompiler\MaterialAssetCompiler.cpp)" warnings (= errors in our configuration) and "1>unrimp\renderer\renderertoolkit\src\assetcompiler\textureassetcompiler.cpp(164): error C2027: use of undefined type 'std::array<std::string,6>'" error to get it compiling again using MSVC